FROM openjdk:17-jdk
ARG JAR_FILE=build/libs/cafe-cok-dev-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} cafe-cok-dev.jar
CMD ["java", "-jar", "-Dspring.profiles.active=prod", "-Duser.timezone=Asia/Seoul", "cafe-cok-dev.jar"]