FROM openjdk:17-jdk
ARG JAR_FILE=build/libs/cafe-cok-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} cafe-cok.jar
CMD ["java", "-jar", "-Dspring.profiles.active=dev", "-Duser.timezone=Asia/Seoul", "cafe-cok.jar"]